export const USER_SIGN_IN_SUCCESS = "USER_SIGN_IN_SUCCESS";
export const USER_SIGN_OUT = "USER_SIGN_OUT";

export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const SET_REDIRECT_TO = "SET_REDIRECT_TO";

export const ORDERS_LOADED = "ORDERS_LOADED";
export const ORDERS_LOADING_START = "ORDERS_LOADING_START";

